### ISSUE TITLE
Open folder by default

### ISSUE THREAD

**Issue by edankwan** [wearekuva/oui#11]
It would be nice to be able to open the folder by default like in dat.GUI:
```js
var gui = oui.datoui();
var fooFolder = gui.addFolder('foo');
fooFolder.open();
```

or 

```js
var gui = oui.datoui();
var fooFolder = gui.addFolder({label: 'foo', isOpen: true});
```

**Comment by marklundin** [comment]
Yep agreed. Folder's can be opened using an `{open:true}` annotation object. The problem was the `addFolder` syntax wasn't accepting it. 

Should be fixed now. For reference, the syntax is:

```javascript
gui.addFolder({label: 'foo', open: true});
```
