### ISSUE TITLE
events support?

### ISSUE THREAD

**Issue by edankwan** [wearekuva/oui#12]
Any plans on events support? Like on update?

**Comment by marklundin** [comment]
Fixed in [120af09](https://github.com/wearekuva/oui/commit/120af0977a63cf58f1d87cb7821b5b362460b7ba).

Oui already supports updates via a callback. This has now been added to datoui. Syntax is:

```javascript
datoui( opts, callback )
```

See the [api](https://github.com/wearekuva/oui/blob/master/docs/api.md)
