### ISSUE TITLE
For control property, if it is a string, treat it as the mapping id

### ISSUE THREAD

**Issue by edankwan** [wearekuva/oui#14]
For example: 
`gui.add( settings, 'color', {control: oui.controls.ColorPicker});`

It seems more user friendly to accept string like:
`gui.add( settings, 'color', {control: 'ColorPicker'});`

If it is a string, it will look for the reference of `oui.controls['ColorPicker']`

**Comment by marklundin** [comment]
Using a reference means you can use custom controllers, such as `gui.add( settings, 'color', {control: MyAwesomeColorPicker})`. Also, I'm not sure it's a good idea having dual type (string|object) parameters.

The ES6 notation has a `@color()` shorthand annotation, so maybe something similar to this for that datoui would be more appropriate. Something like `gui.color( prop, propName )`
