### ISSUE TITLE
Slider input not initialized if value rounds to zero

### ISSUE THREAD

**Issue by mootari** [wearekuva/oui#23]
If the initial value of a slider is 0 (or rounds to 0) the slider input stays empty on first render.

**Comment by mootari** [comment]
Might be related to #23.

**Comment by mootari** [comment]
The cause is again preact's diffAttributes(), although in this case an update to the current preact version might resolve the problem.

**Comment by marklundin** [comment]
Thanks for raising this and filing the bug on Preact. It looks like this should be addressed in [6.1](https://github.com/developit/preact/milestone/10), so I'm tempted to wait for this to land
