### ISSUE TITLE
NumericStepper: min/max attribute not set if attribute equals zero

### ISSUE THREAD

**Issue by mootari** [wearekuva/oui#25]
If a min or max constraint of zero is declared the attribute does not get set on the number input.

**Comment by mootari** [comment]
Might be related to #23.

**Comment by marklundin** [comment]
Good find, and thanks for all the bug testing!

**Comment by mootari** [comment]
After way too much digging I finally found the culprit: preact's diffAttributes() uses a weak comparison when checking the new value against the old. Since the defaults for min and max are "", this result in 0 == "" which evals to true.

**Comment by mootari** [comment]
Created https://github.com/developit/preact/issues/327.

**Comment by marklundin** [comment]
Thanks again. Waiting on Preact [6.1](https://github.com/developit/preact/milestone/10)
