### ISSUE TITLE
The width of the input field is too narrow and it makes it unusable.

### ISSUE THREAD

**Issue by edankwan** [wearekuva/oui#34]
In Windows Chrome, the input field comes with a up/down button that basically block everything:
![num](https://cloud.githubusercontent.com/assets/989103/20832212/deeac3e2-b880-11e6-8551-755991789463.png)

**Comment by marklundin** [comment]
Sure, I think this is a regression. it needs to be disabled in css

**Comment by marklundin** [comment]
Fixed in https://github.com/wearekuva/oui/commit/eade7cbd893868d714ed8b374ca52fe7bd53630b
